### ISSUE TITLE
Thread Exception: Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by SarfarazAliToori** [shubham0204/FaceRecognition_With_FaceNet_Android#12] opened 2021-01-12 07:42 UTC
Hi I am trying to run it on API 21, But in` FrameAnalyser.kt` line no 164 ` boundingBoxOverlay.invalidate()` will through exception.
Please help me I am a beginner Thanks in advance.

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-3
Process: com.example.facerecognition, PID: 12921
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7809)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1338)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:5446)
at android.view.View.invalidateInternal(View.java:14749)
at android.view.View.invalidate(View.java:14713)
at android.view.View.invalidate(View.java:14697)
at com.example.facerecognition.FrameAnalyser$analyze$1$1.run(FrameAnalyser.kt:150)
at java.lang.Thread.run(Thread.java:762)
```

**Comment by shubham0204** [comment] 2021-01-12 15:43
@SarfarazAliToori, please check if the issue is resolved in the [latest commit](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/commit/02df96467876ce886db1f4340b96f494e7987712).

**Comment by SarfarazAliToori** [comment] 2021-01-13 03:43
@shubham0204 It does not work the project is going to crush. I don't know what's the problem.

**Closed** 2021-01-25 17:58 UTC
