### ISSUE TITLE
App crash on samsung

### ISSUE THREAD

**Issue by raja259** [shubham0204/FaceRecognition_With_FaceNet_Android#1] opened 2020-06-25 23:47 UTC
App crashes on samsung mobile where as other ML KIT apps are working

**Comment by shubham0204** [comment] 2020-06-26 14:31
Can you please include your Android version?
If you have built the Android project and then you are running the app on your device, make sure you include the crash logs.

**Comment by handhikadj** [comment] 2020-07-04 13:21
it occurs on mine also. it crashes on my A20 on Android 10

**Comment by shubham0204** [comment] 2020-07-05 01:31
@handhikadj Can you provide crash logs for the same? Also, let me know if you have placed images ( of people you want to recognize ) in an `images` folder in your device's internal storage.

**Comment by handhikadj** [comment] 2020-07-06 11:53
I haven't. but honestly it's annoying that we should use firebase to make it working. can you make it 100% offline?

**Comment by shubham0204** [comment] 2020-07-07 04:34
Firebase MLKit gives us the bounding boxes for all the faces present in the image. We crop these faces and feed them to our FaceNet model. The FaceNet model works best on cropped images ( as unwanted information is discarded by cropping the image ).

**Comment by handhikadj** [comment] 2020-07-07 06:01
i followed this (official) sample:
https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo
the face detection works flawlessly. it provides bounding box, 100% offline and follows the latest technology and API Android has to offer
but the problem is I still don't know how to integrate with tensorflow lite. can you?

**Comment by shubham0204** [comment] 2020-07-07 06:13
@handhikadj , the Android project included in this repo uses the same Firebase MLKit API as the official samples do. The project works offline just as the official sample does.

**Comment by shubham0204** [comment] 2020-07-07 06:14
Do you have any other details regarding this issue? For proposing new features, consider adding a pull request. If you don't have any further details regarding the issue, it would be worth to close this issue.

**Comment by KumaTai** [comment] 2020-08-20 01:55
same problem, here's log:

 Caused by: java.lang.IllegalStateException: imageSubDirs must not be null
        at com.ml.quaterion.facenetdetection.MainActivity.scanStorageForImages(MainActivity.kt:101)
        at com.ml.quaterion.facenetdetection.MainActivity.onRequestPermissionsResult(MainActivity.kt:179)

**Comment by shubham0204** [comment] 2020-08-20 07:33
I have fixed the bug in the [latest commit](https://github.com/shubham0204/FaceRecognition_With_FaceNet_Android/commit/e029031a2cce15369a1b298df55701786ebd4239). Please see if the problem is solved.

**Comment by shubham0204** [comment] 2020-09-17 15:28
As no further details are provided by the participants regarding the latest commit, I am closing this issue for time being.

**Closed** 2020-09-23 08:07 UTC
